# GitGuardian configuration file
# https://docs.gitguardian.com/internal-repositories-monitoring/integrations/git_hooks/pre_commit_pre_push/gitguardian_yml

# Paths to ignore during secret scanning
paths-ignore:
  - .env*
  - node_modules/**
  - .next/**
  - "*.log"

# Allow secrets that have been resolved
allow:
  - commit: aeabdaf
    match: supabase
  - commit: a4800d3
    match: supabase
